// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcAXMvIVoe4-6GHtOVIOQul4JB7vdF-TQ',
    appId: '1:539224314762:web:7b6798442949eced5e6e73',
    messagingSenderId: '539224314762',
    projectId: 'grad-project-dfbe2',
    authDomain: 'grad-project-dfbe2.firebaseapp.com',
    storageBucket: 'grad-project-dfbe2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtaPEuAXvmU7K-VvfF9TSfLEwgYMpzh8o',
    appId: '1:539224314762:android:22db211f1a841b3b5e6e73',
    messagingSenderId: '539224314762',
    projectId: 'grad-project-dfbe2',
    storageBucket: 'grad-project-dfbe2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoeTMwp4qKFgb2bXhbWnvsZASOCWva7-c',
    appId: '1:539224314762:ios:107e4a156bb8aad75e6e73',
    messagingSenderId: '539224314762',
    projectId: 'grad-project-dfbe2',
    storageBucket: 'grad-project-dfbe2.firebasestorage.app',
    iosClientId: '539224314762-rg5bbrrncksoovtji1443j6ub9j28kbk.apps.googleusercontent.com',
    iosBundleId: 'com.example.gradProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoeTMwp4qKFgb2bXhbWnvsZASOCWva7-c',
    appId: '1:539224314762:ios:107e4a156bb8aad75e6e73',
    messagingSenderId: '539224314762',
    projectId: 'grad-project-dfbe2',
    storageBucket: 'grad-project-dfbe2.firebasestorage.app',
    iosClientId: '539224314762-rg5bbrrncksoovtji1443j6ub9j28kbk.apps.googleusercontent.com',
    iosBundleId: 'com.example.gradProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcAXMvIVoe4-6GHtOVIOQul4JB7vdF-TQ',
    appId: '1:539224314762:web:60921e94b5d495185e6e73',
    messagingSenderId: '539224314762',
    projectId: 'grad-project-dfbe2',
    authDomain: 'grad-project-dfbe2.firebaseapp.com',
    storageBucket: 'grad-project-dfbe2.firebasestorage.app',
  );
}
